import Head from "next/head";
import { useRouter } from "next/router";
import isEmpty from "lodash/isEmpty";

import { getAccount } from "/utils/helper";
import { appItems } from "utils/common";

import styles from "/styles/notifications.module.scss";
import AppLayout from "components/layout/AppLayout";

export default function NotificationsPage(props) {
  const { account } = props;
  const router = useRouter();

  return (
    <>
      <Head>
        <title>
          CarePack: Partner and Transact with businesses securely on the
          Blockchain.
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout
        apps={appItems}
        account={account}
        title="Notifications"
        appUrl="notifications"
        appName="Notifications"
      >
        <div className={styles.notifications}>hello</div>
      </AppLayout>
    </>
  );
}

export async function getServerSideProps(ctx) {
  const accountData = await getAccount(ctx, true, true);
  return {
    ...accountData,
    props: {
      ...accountData.props,
    },
  };
}

