import Head from "next/head";
import { useRouter } from "next/router";
import Link from "next/link";
import Image from "next/image";

import { getAccount } from "utils/helper";
import Footer from "components/footer";
import NavBar from "components/navbar";
import AppLayout from "components/layout/AppLayout";
import Button from "components/button";

import { appItems } from "utils/common";

import styles from "styles/inbox.module.scss";
import account from "pages/api/account";

export default function Inbox({ account }) {
  const renderThreads = () => {
    return (
      <li className={styles.thread}>
        <Link href="/inbox/[slug]" as={`/inbox/1234532345543675`}>
          <a className={styles.link}>
            <div className={styles.details}>
              <div className={styles.title}>
                <h3>@Nordstrom</h3>
                <Image
                  src="/images/verify.png"
                  width={16}
                  height={16}
                  layout="fixed"
                  alt="Verified"
                />
              </div>
              <div className={styles.content}>
                <h4 className={styles.subject}>Nordstrom x TDS</h4>
                <p className={styles.blurb}>
                  Hi DigitalSisterHood we would like to partner with you on our
                  next hijab drops...
                </p>
              </div>
            </div>
          </a>
        </Link>
      </li>
    );
  };
  return (
    <>
      <Head>
        <title>
          CarePack: Partner and Transact with businesses securely on the
          Blockchain.
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout
        apps={appItems}
        account={account}
        title="Messages"
        appUrl="inbox"
        appName="Messages"
      >
        <div className={styles.inbox}>
          <div className={styles.wrap}>
            <div className={styles.sidebar}>
              <div className={styles.header}>Conversations</div>
              <ul className={styles.threads}>
                {renderThreads()}
                {renderThreads()}
                {renderThreads()}
                {renderThreads()}
              </ul>
            </div>
            <div className={styles.content}>
              <div className={styles.emptyThread}>
                <i className="material-symbols-outlined">sailing</i>
                <span className={styles.text}>Care Package Inbound.</span>
                <Button type="primary" onClick={() => alert("Open Composer")}>
                  Send a Care Package
                </Button>
              </div>
            </div>
          </div>
        </div>
      </AppLayout>
    </>
  );
}

export async function getServerSideProps(ctx) {
  const accountData = await getAccount(ctx, true, true);

  return {
    ...accountData,
    props: {
      ...accountData.props,
    },
  };
}
