import Head from 'next/head';
import { useRouter } from 'next/router';


import AppLayout from '/components/layout/AppLayout';
import { getAccount } from '/utils/helper';
import { appItems } from 'utils/common';

import styles from '/styles/feed.module.scss';

export default function ExplorePage(props) {
    const {account} = props;
    const router = useRouter();
    const { slug } = router.query;

    const menuItems = [
        {
            name: 'On Going',
            href: '/partners/current',
            icon: 'schedule',
        }, {
            name: 'Requests',
            href: '/partners/requests',
            icon: 'inbox',
        }, {
            name: 'History',
            href: '/partners/history',
            icon: 'history',
        }];

    return (
        <>
            <Head>
                <title>
                    CarePack: Partner and Transact with businesses securely on the
                    Blockchain.
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AppLayout
                account={account}
                slug={slug}
                apps={appItems}
                menu={menuItems}
                appName="Partners"
                appUrl='partners'
                title='Partners'
            >
                Explore
            </AppLayout>
        </>
    );
}

export async function getServerSideProps(ctx) {
    const account = await getAccount(ctx, true, true);
    return account;
}