import Head from 'next/head';
import { useRouter } from 'next/router';


import AppLayout from '/components/layout/AppLayout';
import { getAccount } from '/utils/helper';
import { appItems } from 'utils/common';

import styles from '/styles/feed.module.scss';

export default function ExplorePage(props) {
    const router = useRouter();
    const { slug } = router.query;

    const menuItems = [
        {
            name: 'Brands',
            href: '/explore/brands',
            icon: 'group',
        }, {
            name: 'Drops',
            href: '/explore/drops',
            icon: 'inventory_2',
        }, {
            name: 'Upcoming',
            href: '/home/coming',
            icon: 'today',
        }];

    return (
        <>
            <Head>
                <title>
                    CarePack: Partner and Transact with businesses securely on the
                    Blockchain.
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AppLayout
                account={props.account}
                slug={slug}
                apps={appItems}
                menu={menuItems}
                appName="Explore"
                appUrl='explore'
                title='Explore'
            >
                Explore
            </AppLayout>
        </>
    );
}

export async function getServerSideProps(ctx) {
    const account = await getAccount(ctx, true, true);
    return account;
}