import Head from "next/head";
import Image from 'next/image';
import Link from "next/link";

import {getAccount} from '/utils/helper';

import NavBar from '/components/NavBar';

import styles from "../styles/Home.module.scss";

const Card = ({ username, followers, image, isVerified, url="#" }) => (
  <Link href={url}>
    <a target="_blank" className={styles.card}>
      <Image
        src={image}
        alt={username}
        width={380}
        height={380}
        layout='fixed'
      />
      <div className={styles.metaData}>
        <div className={styles.name}>
          <h2>{username}</h2>
          {isVerified && (<Image
            src="/images/verify.png"
            alt="verify"
            height="20px"
            width="20px"
            layout="fixed"
          />)}
        </div>
        {followers && <h3>{followers} Followers</h3>}
      </div>
    </a>
  </Link>
);

const LandingPage = () => {
  return (
    <>
      <div className={styles.hero}>
        <h1 className={styles.title}>The Web3 Social Space.</h1>
        <h2 className={styles.tag}>
          <span className={styles.blue}>#Discover</span>
          <span className={styles.green}>#Connect</span>
          <span className={styles.red}>#Partner</span>
          <span className={styles.purple}>#Chat</span>
        </h2>
      </div>
      <div className={styles.featured}>
        <div className={styles.wrap}>
          <div className={styles.title}>
            <h1>Build Communities and Partnerships</h1>
            <h2>Grow your community and form Partnerships</h2>
          </div>
          <div className={styles.cards}>
            <Card
              username="@thedigitalsisterhood"
              image="https://lh3.googleusercontent.com/9jwfOBeOcY3rs_KXbtuhN94fU6nD0QMyoxPZTDdK97GTcWohLETM5ElX7a7I4W8L-K12xgtroHpuN6LRuQYh7q0HkuLg2YN1QcXLUzQ=s0"
              isVerified={true}
              url="http://www.thedigitalsisterhood.com"
            />
            <Card
              username="@womenandweapons"
              image="/images/waw.png"
              isVerified={true}
              url="https://opensea.io/collection/womenandweapons"
            />
            <Card
              username="@cryptopunks"
              image="https://lh3.googleusercontent.com/BdxvLseXcfl57BiuQcQYdJ64v-aI8din7WPk0Pgo3qQFhAUH-B6i-dCqqc_mCkRIzULmwzwecnohLhrcH8A9mpWIZqA7ygc52Sr81hE=s0"
              isVerified={true}
              url="https://cryptopunks.app/"
            />
          </div>
        </div>
      </div>
    </>
  );
}

export default function Home(props) {
  return (
    <>
      <Head>
        <title>
          CarePack: Partner and Transact with businesses securely on the
          Blockchain.
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar {...props} />
      <main className={styles.main}>
        <LandingPage />
      </main>
    </>
  );
}

export async function getServerSideProps(ctx) {
  const account = await getAccount(ctx, false, true);
  return account;
}
