import Head from 'next/head'
import LoginBox from '../components/LoginBox';
import { useUser } from '../hooks/useUser';

import styles from '../styles/Login.module.css'

export default function Home() {
  // const { account } = useWeb3React();
  const [viewer, finished] = useUser({ redirectTo: '/home', redirectIfFound: true });
  return (
    <>
      <Head>
        <title>Login | CarePack: Partnerships on the Blockchain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        {finished && !viewer && <LoginBox />}
      </div>
    </>
  )
}