import { useWeb3React } from "@web3-react/core";
import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";

import NavBar from '/components/navbar';

import { truncate_address, getAccount } from "../utils/helper";

import styles from "../styles/Welcome.module.scss";

export default function Welcome(props) {
    const { account: wallet } = useWeb3React();
    const { account } = props;
    const capitalize = s => {
        const name = s.split(" ");
        return name.map(n => n.charAt(0).toUpperCase() + n.substring(1)).join(" ");
    }
    return (
        <>
            <Head>
                <title>
                    Welcome {account.name} | CarePack
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar {...props} />
            <div className={styles.welcome}>
                <h1 className={styles.title}>Welcome {capitalize(account.name)}.</h1>
                <p className={styles.text}>You reserved <span className={styles.username}>@{account.username}</span> successfully!</p>
                <p className={styles.text}>Check back May 27!</p>
            </div>
        </>
    );
};

export async function getServerSideProps(ctx) {
    const account = await getAccount(ctx, true, true);
    return {
        ...account,
    };
}
