import Head from "next/head";
import Link from "next/link";

import { getAccount } from "utils/helper";

import styles from "../styles/Welcome.module.scss";

export default function Welcome(props) {
  const { account } = props;
  const capitalize = (s) => {
    const name = s.split(" ");
    return name
      .map((n) => n.charAt(0).toUpperCase() + n.substring(1))
      .join(" ");
  };
  return (
    <>
      <Head>
        <title>Welcome {account.name} | CarePack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.welcome}>
        <h1 className={styles.title}>Welcome {account.name}</h1>
        <p className={styles.text}>
          <Link href="/explore" className={styles.link}>
            Click to Continue
          </Link>
        </p>
      </div>
    </>
  );
}

export async function getServerSideProps(ctx) {
  const account = await getAccount(ctx, true, true);
  return {
    ...account,
  };
}
