import Head from 'next/head';
import { useRouter } from 'next/router';


import AppLayout from '/components/layout/AppLayout';
import { getAccount } from '/utils/helper';
import { appItems } from 'utils/common';

import styles from '/styles/feed.module.scss';

export default function FeedPage({account}) {
    const router = useRouter();
    const { slug } = router.query;

    const menuItems = [
        {
            name: 'What\'s New',
            href: '/home/for-you',
            icon: 'space_dashboard',
        }, {
            name: 'Trending',
            href: '/home/trending',
            icon: 'mode_heat',
        }, {
            name: 'Insights',
            href: '/home/insights',
            icon: 'insights',
        }];

    return (
        <>
            <Head>
                <title>
                    CarePack: Partner and Transact with businesses securely on the
                    Blockchain.
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AppLayout
                account={account}
                slug={slug}
                apps={appItems}
                menu={menuItems}
                appName="For You"
                appUrl='home'
                showMessages
            >
                Test
            </AppLayout>
        </>
    );
}

export async function getServerSideProps(ctx) {
    const account = await getAccount(ctx, true, true);
    return account;
}