import Head from 'next/head';
import { useRouter } from 'next/router';


import AppLayout from '/components/layout/AppLayout';
import { getAccount } from '/utils/helper';
import { appItems } from 'utils/common';

import styles from '/styles/Settings.module.scss';

export default function SettingsPage(props) {
    const router = useRouter();
    const { slug } = router.query;

    const menuItems = [
        {
            name: 'Profile',
            href: '/settings/account',
            icon: 'account_box',
        }, {
            name: 'Wallet',
            href: '/settings/wallet',
            icon: 'account_balance_wallet',
        }];

    return (
        <>
            <Head>
                <title>
                    CarePack: Partner and Transact with businesses securely on the
                    Blockchain.
                </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AppLayout
                account={props.account}
                slug={slug}
                apps={appItems}
                menu={menuItems}
                appName="Settings"
                appUrl='settings'
                showMessages
            >
                Settings
            </AppLayout>
        </>
    );
}

export async function getServerSideProps(ctx) {
    const account = await getAccount(ctx, true, true);
    return account;
}